apiVersion: v1
kind: Service
metadata:
  labels:
    app: prom-restify-api
  name: prom-restify-api
spec:
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: prom-restify-api
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-apps-http
  namespace: monitoring
  labels:
    k8s-apps: http
    prometheus: kube-prometheus
    release: kube-prometheus
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: prom-restify-api
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http-metrics
    interval: 15s
